### ISSUE TITLE
NoMethodError: undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by ngominhtrint** [slack-ruby/slack-ruby-bot-server-sample#3]
Hi @dblock,

Before it works ok with `rack 1.6.4`. Then, it happens when I run `bundle update`, the rack version is updated by 'kaminari' to `rack 2.0.1` automatically. I ran and got error. Would you please take a look on this. Thank you!

For easy to figure out my problem, I attach some informations:

- With `gem 'rack', '~> 1.6.4'`
I got this one `Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'kaminari' and try again.`

- With gem 'rack', '~> 2.0.1'

When I run, it don't show the slack icon [image link](http://i.imgur.com/KDnjdxV.png), with logs below:

```
10:29:55 web.1  | NoMethodError: undefined method `call' for nil:NilClass
10:29:55 web.1  | Did you mean?  caller
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/file.rb:31:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-server-pages-0.0.6/lib/rack/server_pages.rb:47:in `serving'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-server-pages-0.0.6/lib/rack/server_pages.rb:37:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/tempfile_reaper.rb:15:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/common_logger.rb:33:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/chunked.rb:54:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/rack-2.0.1/lib/rack/content_length.rb:15:in `call'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/bin/unicorn:23:in `load'
10:29:55 web.1  | 	/Users/tringo/Documents/Projects/Rails/slack-ruby-bot-server-sample/vendor/bin/unicorn:23:in `<top (required)>'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
10:29:55 web.1  | 	/Users/tringo/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
10:29:55 web.1  | 127.0.0.1 - - [22/Oct/2016:10:29:55 +0700] "GET /scripts/jquery-1.7.1.min.js HTTP/1.1" 500 104194 0.0171
```

**Comment by dblock** [comment]
It's the same problem as in https://github.com/slack-ruby/slack-ruby-bot-server/pull/31.

**Comment by dblock** [comment]
I have a branch that should fix this and other issues, https://github.com/dblock/rack-server-pages/tree/next

```
gem 'rack-server-pages', github: 'dblock/rack-server-pages', branch: 'next'
```

**Comment by ngominhtrint** [comment]
Thank @dblock, it's really helpful 👍
